### ISSUE TITLE
"Week" view organization

### ISSUE THREAD

**Issue by xenotropic** [azz-eddine/nws_webapp#4]
**(1) Put textual description with temperature on right side.** Similar to point (4) in issue #3. 

**(2) Combine all data for each day into one row.** Having two lines for each day makes it hard to scan, it would be nice if reading down on the left side was just days of the week, like "Today Thursday Friday Saturday . . . ".  To do that, you might consider combining each day into one row, so for example left side is "Thursday" and right side is "Day" superscript over "71 °F, Partly Sunny" and "Night" superscript over "56 °F, Mostly Cloudy".

**Comment by xenotropic** [comment]
Another possibility on (2), instead of merging day and night into one row, would be to alternate the background colors of the rows -- probably making nighttime a darker color. It might be that my original suggestion would create a combined row that looks too cluttered.

**Comment by azz-eddine** [comment]
Hello @xenotropic,

I tried the background solution and i didn't liked the result .. the page was too cluttered ; i mean in my opinion.
I added the icon served from the api to differentiate the daytime and nighttime.. as shown here :

<img width="238" alt="screen shot 2018-08-31 at 23 40 14" src="https://user-images.githubusercontent.com/830747/44938715-63645280-ad78-11e8-98b9-a8ba6151cfb9.png">
